import type { IconProps } from "@phosphor-icons/react";
import {
  Airplane,
  Armchair,
  Baby,
  Bank,
  Brain,
  Buildings,
  Calculator,
  Carrot,
  ChartBar,
  ChartLineUp,
  Coffee,
  Code,
  Compass,
  Confetti,
  Cpu,
  Detective,
  DeviceMobile,
  Eye,
  FirstAid,
  Fish,
  ForkKnife,
  GameController,
  Gear,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Leaf,
  Lock,
  MaskHappy,
  Megaphone,
  Palette,
  PawPrint,
  Pill,
  Robot,
  Scales,
  SoccerBall,
  Storefront,
  Suitcase,
  Syringe,
  Tooth,
  Translate,
  UsersThree,
  VideoCamera,
} from "@phosphor-icons/react";

const CATEGORY_ICONS: Record<string, React.ComponentType<IconProps>> = {
  all: Compass,
  "Vida de campus": Coffee,
  Fiestas: Confetti,
  Deportes: SoccerBall,
  "Gaming y anime": GameController,
  "Música y arte": Headphones,
  Comida: ForkKnife,
  Tablón: Storefront,
  Confesiones: Detective,
  Chisme: Eye,
  Clubes: UsersThree,
  PFADM: Suitcase,
  PFANI: Globe,
  PFAHT: Airplane,
  PFAGN: Leaf,
  PFAND: DeviceMobile,
  PFAQI: Armchair,
  PFAQU: Buildings,
  PFARE: MaskHappy,
  PFBMA: Fish,
  PFCIP: Bank,
  PFCMI: VideoCamera,
  PFCEP: Megaphone,
  PFCMK: ChartLineUp,
  PFCOE: Calculator,
  PFDER: Scales,
  PFDIS: Palette,
  PFEYF: ChartBar,
  PFENI: Globe,
  PFEDU: GraduationCap,
  PFENF: Syringe,
  PFEST: Tooth,
  PFFAR: Pill,
  PFIAM: Leaf,
  PFBIM: FirstAid,
  PFCIB: Lock,
  PFCIV: Hammer,
  PFMIN: Hammer,
  PFISI: Code,
  PFSOF: Cpu,
  PFDIT: Gear,
  PFIEN: ChartBar,
  PFIEC: Cpu,
  PEMSI: Cpu,
  PFIND: Gear,
  PFIAD: Robot,
  PFMKA: Megaphone,
  PFMEH: FirstAid,
  PFMVZ: PawPrint,
  PFNUT: Carrot,
  PFOBS: Baby,
  PFPSI: Brain,
  PFTRA: Translate,
};

export function iconForCategory(id: string): React.ComponentType<IconProps> | null {
  return CATEGORY_ICONS[id] ?? null;
}
