import { Category } from "./types";

export const CATEGORIES: Category[] = [
  { id: "all", name: "Todo el rincón", emoji: "🌀" },
  { id: "Vida de campus", name: "Vida de campus", emoji: "☕", group: "tema" },
  { id: "Fiestas", name: "Fiestas y eventos", emoji: "🎉", group: "tema" },
  { id: "Deportes", name: "Deportes", emoji: "⚽", group: "tema" },
  { id: "Gaming y anime", name: "Gaming y anime", emoji: "🎮", group: "tema" },
  { id: "Música y arte", name: "Música y arte", emoji: "🎧", group: "tema" },
  { id: "Comida", name: "Comida y cafeterías", emoji: "🍟", group: "tema" },
  { id: "Tablón", name: "Compra-venta y roomies", emoji: "📌", group: "tema" },
  { id: "Confesiones", name: "Confesiones", emoji: "🤫", group: "tema" },
  { id: "Chisme", name: "Chisme", emoji: "👀", group: "tema" },
  { id: "Clubes", name: "Clubes y sociedades", emoji: "🎭", group: "tema" },
  { id: "PFADM", name: "Administración de Empresas", emoji: "💼", group: "carrera" },
  { id: "PFANI", name: "Administración de Negocios Internacionales", emoji: "🌐", group: "carrera" },
  { id: "PFAHT", name: "Administración Hotelera y Turismo", emoji: "🏨", group: "carrera" },
  { id: "PFAND", name: "Administración y Negocios Digitales", emoji: "📱", group: "carrera" },
  { id: "PFAGN", name: "Agronomía y Negocios", emoji: "🌾", group: "carrera" },
  { id: "PFAQI", name: "Arquitectura de Interiores", emoji: "🛋️", group: "carrera" },
  { id: "PFAQU", name: "Arquitectura y Urbanismo Ambiental", emoji: "🏙️", group: "carrera" },
  { id: "PFARE", name: "Artes Escénicas", emoji: "🎭", group: "carrera" },
  { id: "PFBMA", name: "Biología Marina", emoji: "🐬", group: "carrera" },
  { id: "PFCIP", name: "Ciencias Políticas y Relaciones Internacionales", emoji: "🏛️", group: "carrera" },
  { id: "PFCMI", name: "Comunicación Audiovisual", emoji: "🎬", group: "carrera" },
  { id: "PFCEP", name: "Comunicación Estratégica y Publicidad Digital", emoji: "📣", group: "carrera" },
  { id: "PFCMK", name: "Comunicación y Marketing", emoji: "📈", group: "carrera" },
  { id: "PFCOE", name: "Contabilidad Empresarial", emoji: "🧮", group: "carrera" },
  { id: "PFDER", name: "Derecho", emoji: "⚖️", group: "carrera" },
  { id: "PFDIS", name: "Diseño Profesional Gráfico", emoji: "🎨", group: "carrera" },
  { id: "PFEYF", name: "Economía y Finanzas", emoji: "💹", group: "carrera" },
  { id: "PFENI", name: "Economía y Negocios Internacionales", emoji: "🌎", group: "carrera" },
  { id: "PFEDU", name: "Educación", emoji: "📚", group: "carrera" },
  { id: "PFENF", name: "Enfermería", emoji: "💉", group: "carrera" },
  { id: "PFEST", name: "Estomatología / Odontología", emoji: "🦷", group: "carrera" },
  { id: "PFFAR", name: "Farmacia y Bioquímica", emoji: "💊", group: "carrera" },
  { id: "PFIAM", name: "Ingeniería Ambiental", emoji: "🌱", group: "carrera" },
  { id: "PFBIM", name: "Ingeniería Biomédica", emoji: "🩻", group: "carrera" },
  { id: "PFCIB", name: "Ingeniería en Ciberseguridad", emoji: "🔐", group: "carrera" },
  { id: "PFCIV", name: "Ingeniería Civil", emoji: "🏗️", group: "carrera" },
  { id: "PFMIN", name: "Ingeniería de Minas", emoji: "⛏️", group: "carrera" },
  { id: "PFISI", name: "Ingeniería de Sistemas de Información", emoji: "💻", group: "carrera" },
  { id: "PFSOF", name: "Ingeniería de Software", emoji: "🖥️", group: "carrera" },
  { id: "PFDIT", name: "Ingeniería en Diseño e Innovación Tecnológica", emoji: "🛠️", group: "carrera" },
  { id: "PFIEN", name: "Ingeniería Económica y de Negocios", emoji: "📊", group: "carrera" },
  { id: "PFIEC", name: "Ingeniería Electrónica", emoji: "🔌", group: "carrera" },
  { id: "PEMSI", name: "Ingeniería Empresarial y de Sistemas", emoji: "🖥️", group: "carrera" },
  { id: "PFIND", name: "Ingeniería Industrial", emoji: "⚙️", group: "carrera" },
  { id: "PFIAD", name: "Ingeniería en Inteligencia Artificial y Ciencia de Datos", emoji: "🤖", group: "carrera" },
  { id: "PFMKA", name: "Marketing y Administración", emoji: "🛍️", group: "carrera" },
  { id: "PFMEH", name: "Medicina Humana", emoji: "🩺", group: "carrera" },
  { id: "PFMVZ", name: "Medicina Veterinaria y Zootecnia", emoji: "🐾", group: "carrera" },
  { id: "PFNUT", name: "Nutrición y Dietética", emoji: "🥕", group: "carrera" },
  { id: "PFOBS", name: "Obstetricia", emoji: "🤰", group: "carrera" },
  { id: "PFPSI", name: "Psicología", emoji: "🧠", group: "carrera" },
  { id: "PFTRA", name: "Traducción e Interpretación", emoji: "🗣️", group: "carrera" },
];

export function formatKarma(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1).replace(/\.0$/, "")}k`;
  return String(Math.max(0, Math.round(n)));
}
